### ISSUE TITLE
every function called on message

### ISSUE THREAD

**Issue by Max-Tweddell** [yotsov/clj-discord#4]
every time a message is received eached function is called, this can mean it can take some time if for example there are db or api requests or that if one of the functions fails it can cause an exception when it wasn't meant to.
One easy solution would be to make the function calls async, which would solve some of the issues.

**Comment by yotsov** [comment]
That's a very good point, will implement soon.

**Comment by Max-Tweddell** [comment]
A quick and easy way is to add a future infront of the function calls 
``
(future (afunction type data))
``
This isn't the best solution but it is a quick and dirty fix

**Comment by yotsov** [comment]
I've been thinking about this, and I think it's not a good idea.

On some Discord servers there are thousands of events per second, and Java threads are expensive. Executing the functions in async mode by default would be a bad idea.

I think the client should know which functions will take a while to execute, and can start a new thread inside the implementations of these functions if the desired behavior is to execute them async.

Is there a reason why you wouldn't want to do this in your client code, and would prefer the library to do it, that I don't see?
